<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-18T13:17:39 IST" name="Default suite" finished-at="2025-01-18T13:17:50 IST" duration-ms="10983">
    <groups>
    </groups>
    <test started-at="2025-01-18T13:17:39 IST" name="Default test" finished-at="2025-01-18T13:17:50 IST" duration-ms="10983">
      <class name="testcases.MavenLoginTest">
        <test-method is-config="true" signature="DataSetUp()[pri:0, instance:testcases.MavenLoginTest@63376bed]" started-at="2025-01-18T13:17:39 IST" name="DataSetUp" finished-at="2025-01-18T13:17:39 IST" duration-ms="477" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataSetUp -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:testcases.MavenLoginTest@63376bed]" started-at="2025-01-18T13:17:39 IST" name="SetUp" finished-at="2025-01-18T13:17:43 IST" duration-ms="3370" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.MavenLoginTest.Logintestfailure()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Logintestfailure()[pri:0, instance:testcases.MavenLoginTest@63376bed]" started-at="2025-01-18T13:17:43 IST" name="Logintestfailure" finished-at="2025-01-18T13:17:49 IST" duration-ms="6218" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The email address or password you have entered is invalid] but found [The email address or password you have entered is invalidfff]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The email address or password you have entered is invalid] but found [The email address or password you have entered is invalidfff]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testcases.MavenLoginTest.Logintestfailure(MavenLoginTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintestfailure -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.MavenLoginTest@63376bed]" started-at="2025-01-18T13:17:49 IST" name="TearDown" finished-at="2025-01-18T13:17:49 IST" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="DataTearDown()[pri:0, instance:testcases.MavenLoginTest@63376bed]" started-at="2025-01-18T13:17:49 IST" name="DataTearDown" finished-at="2025-01-18T13:17:50 IST" duration-ms="255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataTearDown -->
      </class> <!-- testcases.MavenLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
